### ISSUE TITLE
Loading local images

### ISSUE THREAD

**Issue by cryptoboid** [ansh-099/react-native-grid-image-viewer#1]
Hi! I'm building an image gallery with Expo and found your package to be extremely helpful. One thing I realized was that loading locally-available images was kinda tricky, given that the package loads images with `source={{ uri: item.image }}`. I thought about making a PR with the proposed solution for this.

I tried forking and testing a change locally but I keep getting errors with the npm installation (expo cant find the package). I tried installing it locally by cloning and doing `npm install --save ../react-native-grid-image-viewer`. I also tried using `npm link` but same result. 

Given this, I have two questions:
- How do you test your changes locally? Should I use `npm install --save ../react-native-grid-image-viewer`, `npm install --save ../react-native-grid-image-viewer/react-native-grid-image-viewer` or something else? 
- Should I modify this file https://github.com/ansh-099/react-native-grid-image-viewer/blob/master/components/GridImageViewer.js or this file https://github.com/ansh-099/react-native-grid-image-viewer/blob/master/react-native-grid-image-viewer/components/GridImageViewer.js ? I can't understand the difference between each other.

In essence, the change would be adding the parameter `localImage` to the data field, so the new interface would allow for something like this:
```jsx
...
  <GridImageView data={[{ image: 'https://imgur.com/asdasd' }, { localImage: './assets/myfile.png' }]} />
...
```

In the meantime I will be using [this workaround to grab the image URI](https://stackoverflow.com/a/60469521), but well, it would be cool to help you out and offer a new interface 😀

**Comment by ansh-099** [comment]
Hi @cryptoboid,
You need to modify both of them, https://github.com/ansh-099/react-native-grid-image-viewer/blob/master/components/GridImageViewer.js is for testing and https://github.com/ansh-099/react-native-grid-image-viewer/blob/master/react-native-grid-image-viewer/components/GridImageViewer.js is for production.

Cheers!
