### ISSUE TITLE
Remove '.image' from remaining Image source uri values

### ISSUE THREAD

**Issue by dlujan** [ansh-099/react-native-grid-image-viewer#11]
Thank you for addressing my last request! That approach definitely helps my use case and it's simpler than the change I made in my previous PR.

But I am noticing that the remaining Images inside /components/GridImageViewer.js still need to be updated. The images aren't rendering bc of this. Removing the `.image` at lines 132, 156, and 180 fixes this, since `data` now represents an array of urls already.

Thanks again!

**Comment by ansh-099** [comment]
Hi @dlujan,
Thanks for reaching out and reporting the bug. Please check the latest version at https://www.npmjs.com/package/react-native-grid-image-viewer. 

The issue is fixed. Please have a look and if you find any other issue, then please post it.

Cheers!

**Comment by dlujan** [comment]
Perfect! It’s working like a charm now. Thanks so much! I’m very appreciate of your help and also this free package in general. It’s working PERFECTLY for my app.

Cheers!
Daniel
