### ISSUE TITLE
How ca we add Headers?

### ISSUE THREAD

**Issue by ralppppy** [ansh-099/react-native-grid-image-viewer#2]
Hello, This package is great! But is there any way to pass headers when accessing an image? I have a protected endpoint to avoid unauthorized users accessing images.

**Comment by ansh-099** [comment]
Hi @ralppppy,
Currently this option does not exist, nevertheless we've added this issue and fix it quite soon.

**Comment by ansh-099** [comment]
Feature added. Please refer react-native-grid-image-viewer@1.0.7
