### ISSUE TITLE
ReferenceError: Property 'Alert' doesn't exist

### ISSUE THREAD

**Issue by ralppppy** [ansh-099/react-native-grid-image-viewer#3]
When I use the phone back button instead of using the X button to close the modal an error occurred.

ReferenceError: Property 'Alert' doesn't exist

**Comment by ralppppy** [comment]
I really don't know how to create a pull request.

But I think the problem is with this line

onRequestClose={() => {
    Alert.alert("Modal has been closed.");
}}

I've changed it to this.
onRequestClose={() => {
    setModal({ visible: false, data: 0 });
}}

**Comment by ansh-099** [comment]
Hi @ralppppy,

We will fix it for you.
Thanks

**Comment by ansh-099** [comment]
The issue is fixed. Please refer react-native-grid-image-viewer@1.0.7
